### Valid Test Case - High Risk
POST http://localhost:3000/api/predict HTTP/1.1
Content-Type: application/json

{
    "pregnancies": 6,
    "glucose": 195,
    "bloodPressure": 130,
    "skinThickness": 40,
    "insulin": 180,
    "bmi": 37.2,
    "diabetesPedigreeFunction": 0.6,
    "age": 45
}

### Valid Test Case - Low Risk
POST http://localhost:3000/api/predict HTTP/1.1
Content-Type: application/json

{
    "pregnancies": 1,
    "glucose": 85,
    "bloodPressure": 66,
    "skinThickness": 29,
    "insulin": 100,
    "bmi": 23.5,
    "diabetesPedigreeFunction": 0.351,
    "age": 31
}

### Edge Case - Minimum Values
POST http://localhost:3000/api/predict HTTP/1.1
Content-Type: application/json

{
    "pregnancies": 0,
    "glucose": 0,
    "bloodPressure": 0,
    "skinThickness": 0,
    "insulin": 0,
    "bmi": 0,
    "diabetesPedigreeFunction": 0,
    "age": 0
}

### Test Case - Custom Values
POST http://localhost:3000/api/predict HTTP/1.1
Content-Type: application/json

{
    "pregnancies": 5,
    "glucose": 117,
    "bloodPressure": 92,
    "skinThickness": 0,
    "insulin": 0,
    "bmi": 34.1,
    "diabetesPedigreeFunction": 0.337,
    "age": 38
}

### Test Case - Dataset Values
POST http://localhost:3000/api/predict HTTP/1.1
Content-Type: application/json

{
    "pregnancies": 10,
    "glucose": 125,
    "bloodPressure": 70,
    "skinThickness": 26,
    "insulin": 115,
    "bmi": 31.1,
    "diabetesPedigreeFunction": 0.205,
    "age": 41
}


### next server
POST http://localhost:3000/api/predict
Content-Type: application/json

{"pregnancies":7,"glucose":196,"bloodPressure":90,"skinThickness":0,"insulin":0,"bmi":39.8,"diabetesPedigreeFunction":0.451,"age":41}

### python server
POST http://localhost:8000/predict
Content-Type: application/json

{"pregnancies":7,"glucose":196,"bloodPressure":90,"skinThickness":0,"insulin":0,"bmi":39.8,"diabetesPedigreeFunction":0.451,"age":41}


### Test Case - Dataset Values
############################################
## Negative
### 3,126,88,41,235,39.3,0.704,27,0
## Positive
## 7,196,90,0,0,39.8,0.451,41,1

### Test Recommendations - Medium Risk
POST http://localhost:8001/api/recommendations
Content-Type: application/json

{
    "probability": 0.5
}

### Test Recommendations - Low Risk
POST http://localhost:8001/api/recommendations
Content-Type: application/json

{
    "probability": 0.2
}

### Test Recommendations - High Risk
POST http://localhost:8001/api/recommendations
Content-Type: application/json

{
    "probability": 0.8
}