### Valid Test Case - High Risk
POST http://localhost:3000/api/predict HTTP/1.1
Content-Type: application/json

{
    "pregnancies": 6,
    "glucose": 195,
    "bloodPressure": 130,
    "skinThickness": 40,
    "insulin": 180,
    "bmi": 37.2,
    "diabetesPedigreeFunction": 0.6,
    "age": 45
}

### Valid Test Case - Low Risk
POST http://localhost:3000/api/predict HTTP/1.1
Content-Type: application/json

{
    "pregnancies": 1,
    "glucose": 85,
    "bloodPressure": 66,
    "skinThickness": 29,
    "insulin": 100,
    "bmi": 23.5,
    "diabetesPedigreeFunction": 0.351,
    "age": 31
}

### Edge Case - Minimum Values
POST http://localhost:3000/api/predict HTTP/1.1
Content-Type: application/json

{
    "pregnancies": 0,
    "glucose": 0,
    "bloodPressure": 0,
    "skinThickness": 0,
    "insulin": 0,
    "bmi": 0,
    "diabetesPedigreeFunction": 0,
    "age": 0
}

### next server
POST http://localhost:3000/api/predict
Content-Type: application/json

{
    "pregnancies": 1,
    "glucose": 103,
    "bloodPressure": 30,
    "skinThickness": 38,
    "insulin": 83,
    "bmi": 43.3,
    "diabetesPedigreeFunction": 0.183,
    "age": 33
}

### python server
POST http://localhost:8000/predict
Content-Type: application/json

{
    "pregnancies": 1,
    "glucose": 103,
    "bloodPressure": 30,
    "skinThickness": 38,
    "insulin": 83,
    "bmi": 43.3,
    "diabetesPedigreeFunction": 0.183,
    "age": 33
}